"""Guard the hand-maintained install lists against the files on disk.

Every Python module has to be named in `python_sources` / `views_sources`
in `src/jamjar/meson.build`, and every Blueprint in `blueprint_sources`
plus `jamjar.gresource.xml`. Nothing derives those lists from the
directory, so adding a module and forgetting the list is silent: the tree
still runs from source (and so does the pytest suite, which imports via
`PYTHONPATH=src`), because `install_sources` is the only consumer. The
failure surfaces only in an installed prefix — in practice as a Flatpak
that dies on startup, which is how `jamjar.radio` was found missing along
with five other modules.

So this test deliberately reads the meson files as *text* rather than
importing anything: the question isn't "does this module work", it's "is
this filename written down".
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "jamjar"
UI = ROOT / "data" / "ui"

# Generated by configure_file from const.py.in, so it is never a source file.
GENERATED = {"const.py"}


def _files_list(meson_build: Path, var: str) -> set[str]:
    """Extract the quoted names from a `<var> = files(...)` block."""
    text = meson_build.read_text()
    match = re.search(
        rf"^{re.escape(var)}\s*=\s*files\((.*?)^\)", text, re.S | re.M
    )
    if match is None:
        raise AssertionError(f"no `{var} = files(...)` block in {meson_build}")
    return set(re.findall(r"'([^']+)'", match.group(1)))


def _on_disk(directory: Path, pattern: str) -> set[str]:
    return {p.name for p in directory.glob(pattern)}


@pytest.mark.parametrize(
    ("var", "directory", "prefix"),
    [
        ("python_sources", SRC, ""),
        ("views_sources", SRC / "views", "views/"),
    ],
)
def test_python_sources_match_disk(var: str, directory: Path, prefix: str) -> None:
    listed = _files_list(SRC / "meson.build", var)
    expected = {
        f"{prefix}{name}"
        for name in _on_disk(directory, "*.py") - GENERATED
    }
    assert listed == expected, (
        f"{var} is out of sync with {directory.relative_to(ROOT)}: "
        f"missing {sorted(expected - listed)}, stale {sorted(listed - expected)}"
    )


def test_blueprints_match_disk() -> None:
    listed = _files_list(UI / "meson.build", "blueprint_sources")
    expected = _on_disk(UI, "*.blp")
    assert listed == expected, (
        "blueprint_sources is out of sync with data/ui: "
        f"missing {sorted(expected - listed)}, stale {sorted(listed - expected)}"
    )


def test_gresource_lists_every_blueprint() -> None:
    # Compiled .ui files are the only generated entries we check; static
    # assets like style.css are listed by their own name and left alone.
    xml = (UI / "jamjar.gresource.xml").read_text()
    bundled = set(re.findall(r">([^<>]+\.ui)</file>", xml))
    expected = {p.with_suffix(".ui").name for p in UI.glob("*.blp")}
    assert bundled == expected, (
        "jamjar.gresource.xml is out of sync with data/ui: "
        f"missing {sorted(expected - bundled)}, stale {sorted(bundled - expected)}"
    )
